config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'posts#index'
  resources :users, only: [ :show, :edit, :update]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # association
  belongs_to :user
  
  # validation
  validates :title, :post, :user_id, presence: true

  def your_post?(user)
    self.user_id == user.id
  end
end

app/models/user.rb
class User < ApplicationRecord
 has_one_attached :image 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # association
  has_many :posts

  # validation
  validates :nickname, presence: true, length: { maximum: 12 }

  def your_account?(user)
    self.id == user.id
  end
  
  def image_have?
    return self.image.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.includes(:user).order('updated_at DESC').page(params[:page]).per(5)
  end
  
  def show
    @post = Post.includes(:user).find(params[:id])
    @user = @post.user
  end
  
  def new
    @post = Post.new
  end

  def create
    Post.create(create_params)
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.your_post?(current_user)
      post.update(update_params)
    end
    redirect_to action: :index
  end
  
  def destroy
    post = Post.find(params[:id])
    if post.your_post?(current_user)
      post.destroy
    end
    redirect_to action: :index
  end
  
  private
  def create_params
    params.require(:post).permit(:title, :post).merge(user_id: current_user.id)
  end
  
  def update_params
    params.require(:post).permit(:title, :post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: :sign_in

  def show
    @user = User.includes(:posts).find(params[:id])
    @posts = Post.order('created_at DESC').where(user_id: params[:id]).page(params[:page]).per(5)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    user = User.find(params[:id])
    if user.your_account?(current_user)
      user.update(update_params)
      redirect_to action: :show
    end
  end
  
  private
  def update_params
    params.require(:user).permit(:nickname, :email, :text, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_footer.html.erb
  <div class="footer-copyright center-align">
    <div class="container">
    &copy; 2019 riririusei99
    </div>
  </div>

app/views/common/_header.html.erb
<header>
  <nav class="blue lighten-1 row">
    <div class="nav-wrapper col s10 offset-s1">
      <a href="/" class="brand-logo"><i class="material-icons">border_color</i>Blog</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if user_signed_in? %>
          <li><%= link_to "Post Blog", "/posts/new", method: :get %></li>
          <li><%= link_to "My Page", "/users/#{current_user.id}", method: :get %></li>
          <li><%= link_to "Sing out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sing in", new_user_session_path, method: :get  %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  </head>
  <body>
    <%= render partial: 'common/header' %>
    <div class="container"> 
    <% if notice != nil || alert != nil %>
      <div class="message-area">
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      </div>
      <% end  %>
    <%= yield %>
    </div>
    <%= render partial: 'common/footer' %>
  </body>
</html>

app/views/posts/_post.html.erb
  <div class="row">
    <div class="col s12 m12">
      <div class="card blue-text text-darken-2">
        <div class="card-content">
          <span class="card-title"><%= post.title %></span>
          <p class="grey-text text-darken-2" ><%= post.post %></p>
          <h6 class="right-align grey-text text-lighten-1"><%= "#{post.user.nickname} (#{post.created_at}) " %></h6>
        </div>
        
        <div class="card-action right-align ">
          <%= link_to "Show", post_path(post), class: "waves-effect waves-light btn blue lighten-1" %>
          <% if  user_signed_in? && post.your_post?(current_user) %>
            <%= link_to "Edit", edit_post_path(post), class: "waves-effect waves-light btn blue lighten-1"  %>
            <%= link_to "Delete", "/posts/#{post.id}", method: :delete, data: { confirm: '投稿を削除します。よろしいですか？' }, class: "waves-effect waves-light btn blue lighten-1"  %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  

app/views/posts/create.html.erb
投稿が完了しました。
<a href="/">Back to Top</a>

app/views/posts/edit.html.erb
<div class="row">
    <%= form_for @post do |f|  %>
      <div class="input-field col s6">
        <%= f.text_field :title, placeholder: @post.title , class: "validate" %>
        <label for="Title">Title</label>
      </div>
      <div class="input-field col s12">
        <%= f.text_area :post, placeholder: @post.post , class: "materialize-textarea" %>
        <label for="textarea1">Post</label>
      </div>
      <div class="input-field col s12">
        <button class="btn waves-effect waves-light" type="submit">Update Post
          <i class="material-icons right">send</i>
        </button>
      </div>
    <% end %>
</div>

app/views/posts/index.html.erb
  <div class="row">
    <div class="col s12 m12">
      <h3>New Post.</h3>
      <div class="divider"></div>
      <div class="section">
      <%= render partial: "posts/post", collection: @posts %>
      </div>
      <div class="divider"></div>
      <div class="row center-align">
        <%= paginate(@posts) %>
      </div>
    </div>
  </div>

app/views/posts/new.html.erb
<div class="row">
    <%= form_for(@post) do |f|  %>
      <div class="input-field col s6">
        <%= f.text_field :title, placeholder: "sample title", class: "validate" %>
        <label for="Title">Title</label>
      </div>
      <div class="input-field col s12">
        <%= f.text_area :post, placeholder: "Write something this", class: "materialize-textarea" %>
        <label for="textarea1">Post</label>
      </div>
      <div class="input-field col s12">
        <button class="btn waves-effect waves-light" type="submit">Post Blog
          <i class="material-icons right">create</i>
        </button>
      </div>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col s12 m12">
      <h4><%= @post.title %></h4>
  </div>
  <div class="col s12 m12">
    <div class="divider"></div>
    <!--card contents-->
    <div class="row">
      <div class="col s12 m12">
        <div class="card ">
          <div class="card-content white-text">
            <!--<span class="card-title">Card Title</span>-->
            <p class="grey-text text-darken-2 flow-text"><%= @post.post %></p>
          </div>
          <div class="card-action">
            <% if  user_signed_in? && @post.your_post?(current_user) %>
              <%= link_to "Edit", edit_post_path(@post), class: "waves-effect waves-light btn blue lighten-1"  %>
              <%= link_to "Delete", "/posts/#{@post.id}", method: :delete, data: { confirm: '投稿を削除します。よろしいですか？' }, class: "waves-effect waves-light btn blue lighten-1"  %>
            <% end %>
            <h6 class="right-align grey-text text-lighten-1"><%= "created: #{@post.created_at} " %></h6>
          </div>
        </div>
      </div>
    </div>
    <!-- card_end -->
    <h4>Posted by</h4>
    <div class="divider"></div>
    <%= render partial: "users/user", collection: [@post.user] %>
  </div>
</div>

app/views/users/_user.html.erb
<div class="row"> 
  <div class="col s12 m12">
    <div class="card horizontal">
      <div class="card-image col s2">
        <% if user.image_have? %>
          <%= image_tag rails_blob_path(user.image), class:"profile-img" %>
        <% else %>
          <%= image_tag 'image1.jpg' %>
        <% end %>
      </div>
      <div class="card-stacked col s10">
        <div class="card-content">
          <h5><%= user.nickname %></h5>
          <p><%= user.text %></p>
        </div>
        <div class="card-action">
          <%= link_to "show more", user_path(user.id) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row ">
  <%= form_for @user do |f|  %>
    <div class="row">
      <div class="input-field col s6">
        <i class="material-icons prefix">account_circle</i>
        <%= f.text_field :nickname, placeholder: @user.nickname , class: "validate" %>
        <label for="icon_prefix">Nickame</label>
      </div>
      <div class="input-field col s6">
        <i class="material-icons prefix">email</i>
        <%= f.text_field :email, placeholder: @user.email , class: "validate" %>
        <br>
        <label for="email">Email</label>
      </div>
      <div class="input-field col s12">
        <%= f.text_field :text, placeholder: "free comment" %>
        <label for="Title">Free text</label>
      </div>
      <div class="input-field col s12">
        <%= f.file_field :image,placeholder: "upload image file" %>
      </div>
      <div class="input-field col s12">
        <button class="btn waves-effect waves-light" type="submit">Change Profile
          <i class="material-icons right">send</i>
        </button>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="row"> 
  <div class="col s12 m12">
    <h4 class="header">Profile</h4>
    <div class="divider"></div>
    <%= render partial: "users/user", collection: [@user] %>
    <% if @user.your_account?(current_user)%>
    <p><i class="small material-icons">account_box</i><%= link_to "Edit your profile", edit_user_path(current_user) %></p>
    <% end%>
    <h4 class="header">Post list</h4>
    <div class="divider"></div>
    <%= render partial: "posts/post", collection: @posts %>
    <div class="divider"></div>
    <div class="row center-align">
      <%= paginate(@posts) %>
    </div>
  </div>
</div>